import test from 'node:test';
import assert from 'node:assert/strict';
import {extractClaims,parseHar,audit,exportReport,reportMarkdown} from '../dist/engine.js';
import {EXAMPLES} from '../dist/examples.js';
const har=(body,extra={})=>({log:{entries:[{request:{url:'https://private.example.test/secret',method:'POST',postData:{mimeType:'application/json',text:JSON.stringify(body)},...extra},response:{status:200}}]}});
const run=(policy,input,edit=()=>{})=>{const claims=extractClaims(policy);edit(claims);return audit({policy,claims,capture:parseHar(input)});};
const locationPolicy='We never transmit precise location.';
const emailPolicy='We do not collect email addresses.';
const idPolicy='We never collect device identifiers.';
const first=(policy,input)=>run(policy,input).findings[0];
test('three demos establish contradiction, match, and abstention',()=>{const expected={conflict:{conflict:2,matched:1,undisclosed:0,unobserved:0,unknown:0},matching:{conflict:0,matched:3,undisclosed:0,unobserved:0,unknown:0},opaque:{conflict:0,matched:0,undisclosed:0,unobserved:0,unknown:2}};for(const [key,x]of Object.entries(EXAMPLES))assert.deepEqual(run(x.policy,x.har).counts,expected[key]);});
test('policy quote offsets preserve source, including whitespace and Unicode',()=>{const policy='  我们不会收集邮箱地址。\n\nWe collect device identifiers.';const claims=extractClaims(policy);assert.equal(claims.length,2);for(const c of claims)assert.equal(policy.slice(c.start,c.end),c.quote);assert.equal(claims[0].mode,'deny');assert.equal(claims[1].line,3);});
for(const sentence of ['We do not collect email addresses unless you consent.','We collect email addresses only after you sign in.','We share email addresses with partners.','We no longer collect email addresses.','Do we collect email addresses?','Other apps collect email addresses.','We cannot collect email addresses.','We may not collect email addresses.'])test('abstain on policy context: '+sentence,()=>{assert.equal(first(sentence,har({email:'alice@example.test'})).status,'unknown');});
test('contradictory policy clauses cannot produce a passing match',()=>{assert.equal(first('We collect email addresses. We do not collect email addresses.',har({email:'alice@example.test'})).status,'unknown');});
for(const sentence of ['We never collect email addresses for advertising.','We never send email addresses to our servers.','We never collect email addresses from children.'])test('scoped denial requires review: '+sentence,()=>assert.equal(first(sentence,har({email:'a@b.test'})).status,'unknown'));
test('excluded positive claim cannot override a denial',()=>{const r=run('We collect email addresses. We never collect email addresses.',har({email:'alice@example.test'}),claims=>claims[0].included=false);assert.equal(r.findings[0].status,'conflict');});
test('genuine visible data without a recognized claim needs disclosure review',()=>{assert.equal(first('Privacy is important to our team.',har({email:'alice@example.test'})).status,'undisclosed');});
test('absence is reported as not observed, never as a passing match',()=>{assert.equal(first(emailPolicy,har({event:'open'})).status,'unobserved');});
test('missing POST payload must abstain',()=>{assert.equal(first(emailPolicy,har(null,{postData:undefined,bodySize:99})).status,'unknown');});
test('unsupported binary payload must abstain',()=>{assert.equal(first(emailPolicy,har(null,{postData:{mimeType:'application/octet-stream',text:'binary-data'}})).status,'unknown');});
test('malformed JSON request body must abstain',()=>{assert.equal(first(emailPolicy,har(null,{postData:{mimeType:'application/json',text:'{broken'}})).status,'unknown');});
test('response bodies never masquerade as outbound evidence',()=>{const x=har({event:'open'});x.log.entries[0].response.content={text:'{"email":"alice@example.test"}'};assert.equal(first(emailPolicy,x).status,'unobserved');});
test('email key alone is insufficient',()=>{assert.equal(first(emailPolicy,har({email:'[redacted]'})).status,'unobserved');});
test('email hidden in an arbitrary field is outside stated detector scope',()=>{assert.equal(first(emailPolicy,har({unrecognized:'alice@example.test'})).status,'unobserved');});
test('valid email in URL query is detected',()=>{assert.equal(first(emailPolicy,har(null,{method:'GET',postData:undefined,url:'https://example.test/path?email=alice%40example.test'})).status,'conflict');});
test('HAR queryString records are supported',()=>{assert.equal(first(emailPolicy,har({}, {queryString:[{name:'email',value:'alice@example.test'}]})).status,'conflict');});
test('form-encoded body is supported',()=>{assert.equal(first(emailPolicy,har(null,{postData:{mimeType:'application/x-www-form-urlencoded',text:'email=alice%40example.test'}})).status,'conflict');});
test('HAR form params are supported',()=>{assert.equal(first(emailPolicy,har(null,{postData:{mimeType:'multipart/form-data',params:[{name:'email',value:'alice@example.test'}]}})).status,'conflict');});
test('precise coordinate pair is detected',()=>{assert.equal(first(locationPolicy,har({latitude:25.0339,longitude:121.5645})).status,'conflict');});
test('single latitude is insufficient',()=>{assert.equal(first(locationPolicy,har({latitude:25.0339})).status,'unobserved');});
test('coordinates must be siblings',()=>{assert.equal(first(locationPolicy,har({a:{lat:25.0339},b:{lon:121.5645}})).status,'unobserved');});
test('coarse coordinates are not classified as precise',()=>{assert.equal(first(locationPolicy,har({lat:25.03,lon:121.56})).status,'unobserved');});
test('both coordinates must have sufficient decimal resolution',()=>{assert.equal(first(locationPolicy,har({lat:25,lon:121.5645})).status,'unobserved');});
test('out-of-range coordinates are rejected',()=>{assert.equal(first(locationPolicy,har({lat:125.0339,lon:221.5645})).status,'unobserved');});
test('null and boolean coordinates are rejected',()=>{for(const body of [{lat:null,lon:121.5645},{lat:true,lon:121.5645}])assert.equal(first(locationPolicy,har(body)).status,'unobserved');});
test('nested arrays support known device identifier fields',()=>{assert.equal(first(idPolicy,har({events:[{device_id:'SAMPLE-IDENTIFIER-100'}]})).status,'conflict');});
test('zero advertising IDs and placeholders are not evidence',()=>{for(const value of ['00000000-0000-0000-0000-000000000000','[redacted]','unknown',null,true,''])assert.equal(first(idPolicy,har({device_id:value})).status,'unobserved');});
test('truncated deep objects abstain',()=>{let obj={email:'alice@example.test'};for(let i=0;i<20;i++)obj={nested:obj};assert.equal(first(emailPolicy,har(obj)).status,'unknown');});
test('tampered policy quotations are rejected',()=>{const policy=emailPolicy;const claims=extractClaims(policy);claims[0].quote='Made-up quote';assert.throws(()=>audit({policy,claims,capture:parseHar(har({email:'a@b.test'}))}),/no longer matches/);});
test('invalid interpretations are rejected',()=>{assert.throws(()=>run(emailPolicy,har({email:'a@b.test'}),c=>c[0].mode='compliant'),/invalid/);});
test('unknown hosts and raw values are absent from parsed capture',()=>{const x=har({email:'private-secret@example.test',device_id:'secret-device-987',lat:25.0339,lon:121.5645});x.log.entries[0].request.headers=[{name:'Authorization',value:'Bearer secret-token'}];const output=JSON.stringify(parseHar(x));for(const secret of ['private-secret@example.test','secret-device-987','25.0339','121.5645','secret-token','private.example.test','/secret'])assert.equal(output.includes(secret),false,secret);});
test('portable exports omit free text, arbitrary object keys, and raw values',()=>{const policy='We do not collect email addresses for person@example.test.';const input=har({'private-key@example.test':{email:'alice@example.test'}});const r=run(policy,input);r.context='private-note@example.test';for(const out of [JSON.stringify(exportReport(r)),reportMarkdown(r)])for(const secret of ['person@example.test','private-key@example.test','alice@example.test','private-note@example.test','private.example.test'])assert.equal(out.includes(secret),false,secret);assert.match(reportMarkdown(r),/character offsets/);});
test('portable export never mutates the in-browser evidence',()=>{const r=run(emailPolicy,har({email:'a@b.test'}));exportReport(r);assert.equal(r.findings[0].claims[0].quote,emailPolicy);assert.ok(r.findings[0].evidence[0].path.endsWith('.email'));});
for(const [name,value] of [['invalid JSON','{'],['missing log',{}],['missing entries',{log:{}}],['empty capture',{log:{entries:[]}}],['missing URL',{log:{entries:[{request:{}}]}}],['non-http URL',har({}, {url:'javascript:alert(1)'})]])test('reject '+name,()=>assert.throws(()=>parseHar(value)));
test('too many requests are rejected before expensive parsing',()=>assert.throws(()=>parseHar({log:{entries:Array(5001).fill({})}}),/5,000/));
test('too-large file is rejected before JSON parsing',()=>assert.throws(()=>parseHar('x'.repeat(10*1024*1024+1)),/10 MB/));
test('policy input has a bounded size',()=>assert.throws(()=>extractClaims('x'.repeat(200001)),/200,000/));
