import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true}); const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1080}});
const page=await context.newPage();const errors=[];const outbound=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173')&&!r.url().startsWith('blob:'))outbound.push(r.url());});
await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.registeredTools[tool.name]=tool;}}});});
const results=[];
const check=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('PASS '+name);};
try{
 await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
 await check('empty state and disabled action',async()=>assert.equal(await page.locator('#review-button').isDisabled(),true));
 await page.screenshot({path:'artifacts/policytrace-desktop.png',fullPage:true});
 for(const [key,counts]of Object.entries({conflict:[2,1,0],matching:[0,3,0],opaque:[0,0,2]})){
  await check('full demo flow: '+key,async()=>{await page.locator(`.demo-button[data-demo=${key}]`).click();assert.equal(await page.locator('#run-button').isDisabled(),true);await page.locator('#confirm-claims').check();await page.locator('#run-button').click();assert.deepEqual(await page.locator('.metric strong').allTextContents(),counts.map(x=>String(x).padStart(2,'0')));});
  if(key==='conflict')await page.screenshot({path:'artifacts/policytrace-evidence.png',fullPage:true});
 }
 await check('download contains safe report and real status',async()=>{const wait=page.waitForEvent('download');await page.locator('#export-json').click();const download=await wait;await download.saveAs('artifacts/downloaded-report.json');const stream=await download.createReadStream();let data='';for await(const chunk of stream)data+=chunk;const report=JSON.parse(data);assert.equal(report.counts.unknown,2);assert.equal(JSON.stringify(report).includes('Cedar Notes'),false);});
 await check('export fingerprints bind to actual inputs',async()=>{const hashes=await page.evaluate(async()=>{const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');return {policy:await hash(document.querySelector('#policy').value)};});const data=JSON.parse(await (await import('node:fs/promises')).readFile('artifacts/downloaded-report.json','utf8'));assert.equal(data.inputFingerprints.policy,hashes.policy);assert.match(data.inputFingerprints.har,/^[a-f0-9]{64}$/);});
 await check('policy edit invalidates stale results',async()=>{await page.locator('#policy').fill('We collect email addresses.');assert.equal(await page.locator('.report').count(),0);});
 await check('malformed HAR shows useful error and clears old capture',async()=>{await page.locator('#har-file').setInputFiles({name:'broken.har',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.locator('#input-error').waitFor({state:'visible'});assert.match(await page.locator('#input-error').innerText(),/not valid JSON/);assert.equal(await page.locator('#review-button').isDisabled(),true);});
 await check('import own HAR and policy, including XSS-like content',async()=>{const policy='We never collect email addresses. <img src=x onerror="window.injection=1">';await page.locator('#policy').fill(policy);const har={log:{entries:[{request:{url:'https://private.example.test/private?token=SECRET_TOKEN',method:'POST',postData:{mimeType:'application/json',text:JSON.stringify({email:'PRIVATE_EMAIL@example.test'})}}}]}};await page.locator('#har-file').setInputFiles({name:'private.har',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(har))});await page.locator('#review-button').click();await page.locator('#confirm-claims').check();await page.locator('#run-button').click();assert.equal(await page.locator('.status.conflict').count(),1);assert.equal(await page.evaluate(()=>window.injection),undefined);assert.equal((await page.locator('#results-content').innerText()).includes('PRIVATE_EMAIL'),false);assert.equal((await page.locator('#results-content').innerText()).includes('SECRET_TOKEN'),false);});
 await check('local destination inspection reveals only hostnames',async()=>{await page.locator('#show-destinations').click();const text=await page.locator('#dialog-body').innerText();assert.ok(text.includes('private.example.test'));assert.equal(text.includes('SECRET_TOKEN'),false);await page.keyboard.press('Escape');});
 await check('claim edits require renewed confirmation',async()=>{await page.locator('#edit-claims').click();await page.locator('#confirm-claims').check();await page.locator('[data-claim-mode]').first().selectOption('review');assert.equal(await page.locator('#run-button').isDisabled(),true);});
 await check('manual policy selection adds a verifiable claim',async()=>{await page.locator('#policy').evaluate(el=>{el.focus();el.setSelectionRange(0,32)});await page.locator('#add-claim').click();assert.equal(await page.locator('.claim-card').count(),2);});
 await check('clear removes all review state',async()=>{await page.locator('#clear-button').click();assert.equal(await page.locator('#policy').inputValue(),'');assert.equal(await page.locator('.report').count(),0);assert.equal(await page.locator('#review-button').isDisabled(),true);});
 await check('dialog keyboard escape',async()=>{await page.locator('#method-button').click();assert.equal(await page.locator('#info-dialog').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#info-dialog').isVisible(),false);});
 await check('WebMCP registration, state update, read-back and rejection in registry harness',async()=>{const data=await page.evaluate(async()=>{const tools=window.registeredTools;const loaded=await tools.load_privacy_audit_example.execute({example:'opaque'});const read=await tools.read_privacy_audit_summary.execute({});let invalid=false;try{await tools.load_privacy_audit_example.execute({example:'invalid'})}catch{invalid=true}return{names:Object.keys(tools),loaded,read,invalid};});assert.equal(data.names.length,2);assert.equal(data.loaded.example,'opaque');assert.equal(data.read.completed,false);assert.equal(data.invalid,true);assert.equal(await page.locator('.claim-card').count(),2);});
 for(const width of [390,768,1440])await check(`responsive layout at ${width}px`,async()=>{await page.setViewportSize({width,height:900});await page.locator('#confirm-claims').check();await page.locator('#run-button').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);if(width===390)await page.screenshot({path:'artifacts/policytrace-mobile.png',fullPage:true});await page.locator('#edit-claims').click();});
 await check('no unexpected network transmission or browser exceptions',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(outbound,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);});
 await writeFile('artifacts/browser-results.json',JSON.stringify({passed:results.length,results,errors,outbound,webMcp:'Registry harness only; native WebMCP browser implementation unavailable.'},null,2));
}catch(e){await page.screenshot({path:'artifacts/browser-failure.png',fullPage:true});console.error(e);process.exitCode=1;}finally{await browser.close();}
